// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: osi_occupant.proto

#include "osi_occupant.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace osi3 {
constexpr Occupant_Classification::Occupant_Classification(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : is_driver_(false)
  , seat_(0)

  , steering_control_(0)
{}
struct Occupant_ClassificationDefaultTypeInternal {
  constexpr Occupant_ClassificationDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~Occupant_ClassificationDefaultTypeInternal() {}
  union {
    Occupant_Classification _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT Occupant_ClassificationDefaultTypeInternal _Occupant_Classification_default_instance_;
constexpr Occupant::Occupant(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : source_reference_()
  , id_(nullptr)
  , classification_(nullptr){}
struct OccupantDefaultTypeInternal {
  constexpr OccupantDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~OccupantDefaultTypeInternal() {}
  union {
    Occupant _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT OccupantDefaultTypeInternal _Occupant_default_instance_;
}  // namespace osi3
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_osi_5foccupant_2eproto[2];
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_osi_5foccupant_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_osi_5foccupant_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_osi_5foccupant_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::osi3::Occupant_Classification, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::osi3::Occupant_Classification, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::osi3::Occupant_Classification, is_driver_),
  PROTOBUF_FIELD_OFFSET(::osi3::Occupant_Classification, seat_),
  PROTOBUF_FIELD_OFFSET(::osi3::Occupant_Classification, steering_control_),
  0,
  1,
  2,
  PROTOBUF_FIELD_OFFSET(::osi3::Occupant, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::osi3::Occupant, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::osi3::Occupant, id_),
  PROTOBUF_FIELD_OFFSET(::osi3::Occupant, classification_),
  PROTOBUF_FIELD_OFFSET(::osi3::Occupant, source_reference_),
  0,
  1,
  ~0u,
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 9, -1, sizeof(::osi3::Occupant_Classification)},
  { 12, 21, -1, sizeof(::osi3::Occupant)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::osi3::_Occupant_Classification_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::osi3::_Occupant_default_instance_),
};

const char descriptor_table_protodef_osi_5foccupant_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\022osi_occupant.proto\022\004osi3\032\020osi_common.p"
  "roto\"\232\006\n\010Occupant\022\034\n\002id\030\001 \001(\0132\020.osi3.Ide"
  "ntifier\0225\n\016classification\030\002 \001(\0132\035.osi3.O"
  "ccupant.Classification\0221\n\020source_referen"
  "ce\030\003 \003(\0132\027.osi3.ExternalReference\032\205\005\n\016Cl"
  "assification\022\021\n\tis_driver\030\002 \001(\010\0220\n\004seat\030"
  "\003 \001(\0162\".osi3.Occupant.Classification.Sea"
  "t\022G\n\020steering_control\030\004 \001(\0162-.osi3.Occup"
  "ant.Classification.SteeringControl\"\367\001\n\004S"
  "eat\022\020\n\014SEAT_UNKNOWN\020\000\022\016\n\nSEAT_OTHER\020\001\022\023\n"
  "\017SEAT_FRONT_LEFT\020\002\022\024\n\020SEAT_FRONT_RIGHT\020\003"
  "\022\025\n\021SEAT_FRONT_MIDDLE\020\004\022\022\n\016SEAT_BACK_LEF"
  "T\020\005\022\023\n\017SEAT_BACK_RIGHT\020\006\022\024\n\020SEAT_BACK_MI"
  "DDLE\020\007\022\027\n\023SEAT_THIRD_ROW_LEFT\020\010\022\030\n\024SEAT_"
  "THIRD_ROW_RIGHT\020\t\022\031\n\025SEAT_THIRD_ROW_MIDD"
  "LE\020\n\"\352\001\n\017SteeringControl\022\034\n\030STEERING_CON"
  "TROL_UNKNOWN\020\000\022\032\n\026STEERING_CONTROL_OTHER"
  "\020\001\022\034\n\030STEERING_CONTROL_NO_HAND\020\002\022\035\n\031STEE"
  "RING_CONTROL_ONE_HAND\020\003\022\037\n\033STEERING_CONT"
  "ROL_BOTH_HANDS\020\004\022\036\n\032STEERING_CONTROL_LEF"
  "T_HAND\020\005\022\037\n\033STEERING_CONTROL_RIGHT_HAND\020"
  "\006B\002H\001"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_osi_5foccupant_2eproto_deps[1] = {
  &::descriptor_table_osi_5fcommon_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_osi_5foccupant_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_osi_5foccupant_2eproto = {
  false, false, 845, descriptor_table_protodef_osi_5foccupant_2eproto, "osi_occupant.proto", 
  &descriptor_table_osi_5foccupant_2eproto_once, descriptor_table_osi_5foccupant_2eproto_deps, 1, 2,
  schemas, file_default_instances, TableStruct_osi_5foccupant_2eproto::offsets,
  file_level_metadata_osi_5foccupant_2eproto, file_level_enum_descriptors_osi_5foccupant_2eproto, file_level_service_descriptors_osi_5foccupant_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_osi_5foccupant_2eproto_getter() {
  return &descriptor_table_osi_5foccupant_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_osi_5foccupant_2eproto(&descriptor_table_osi_5foccupant_2eproto);
namespace osi3 {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Occupant_Classification_Seat_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_osi_5foccupant_2eproto);
  return file_level_enum_descriptors_osi_5foccupant_2eproto[0];
}
bool Occupant_Classification_Seat_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
constexpr Occupant_Classification_Seat Occupant_Classification::SEAT_UNKNOWN;
constexpr Occupant_Classification_Seat Occupant_Classification::SEAT_OTHER;
constexpr Occupant_Classification_Seat Occupant_Classification::SEAT_FRONT_LEFT;
constexpr Occupant_Classification_Seat Occupant_Classification::SEAT_FRONT_RIGHT;
constexpr Occupant_Classification_Seat Occupant_Classification::SEAT_FRONT_MIDDLE;
constexpr Occupant_Classification_Seat Occupant_Classification::SEAT_BACK_LEFT;
constexpr Occupant_Classification_Seat Occupant_Classification::SEAT_BACK_RIGHT;
constexpr Occupant_Classification_Seat Occupant_Classification::SEAT_BACK_MIDDLE;
constexpr Occupant_Classification_Seat Occupant_Classification::SEAT_THIRD_ROW_LEFT;
constexpr Occupant_Classification_Seat Occupant_Classification::SEAT_THIRD_ROW_RIGHT;
constexpr Occupant_Classification_Seat Occupant_Classification::SEAT_THIRD_ROW_MIDDLE;
constexpr Occupant_Classification_Seat Occupant_Classification::Seat_MIN;
constexpr Occupant_Classification_Seat Occupant_Classification::Seat_MAX;
constexpr int Occupant_Classification::Seat_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Occupant_Classification_SteeringControl_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_osi_5foccupant_2eproto);
  return file_level_enum_descriptors_osi_5foccupant_2eproto[1];
}
bool Occupant_Classification_SteeringControl_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
constexpr Occupant_Classification_SteeringControl Occupant_Classification::STEERING_CONTROL_UNKNOWN;
constexpr Occupant_Classification_SteeringControl Occupant_Classification::STEERING_CONTROL_OTHER;
constexpr Occupant_Classification_SteeringControl Occupant_Classification::STEERING_CONTROL_NO_HAND;
constexpr Occupant_Classification_SteeringControl Occupant_Classification::STEERING_CONTROL_ONE_HAND;
constexpr Occupant_Classification_SteeringControl Occupant_Classification::STEERING_CONTROL_BOTH_HANDS;
constexpr Occupant_Classification_SteeringControl Occupant_Classification::STEERING_CONTROL_LEFT_HAND;
constexpr Occupant_Classification_SteeringControl Occupant_Classification::STEERING_CONTROL_RIGHT_HAND;
constexpr Occupant_Classification_SteeringControl Occupant_Classification::SteeringControl_MIN;
constexpr Occupant_Classification_SteeringControl Occupant_Classification::SteeringControl_MAX;
constexpr int Occupant_Classification::SteeringControl_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)

// ===================================================================

class Occupant_Classification::_Internal {
 public:
  using HasBits = decltype(std::declval<Occupant_Classification>()._has_bits_);
  static void set_has_is_driver(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_seat(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_steering_control(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
};

Occupant_Classification::Occupant_Classification(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:osi3.Occupant.Classification)
}
Occupant_Classification::Occupant_Classification(const Occupant_Classification& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&is_driver_, &from.is_driver_,
    static_cast<size_t>(reinterpret_cast<char*>(&steering_control_) -
    reinterpret_cast<char*>(&is_driver_)) + sizeof(steering_control_));
  // @@protoc_insertion_point(copy_constructor:osi3.Occupant.Classification)
}

void Occupant_Classification::SharedCtor() {
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&is_driver_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&steering_control_) -
    reinterpret_cast<char*>(&is_driver_)) + sizeof(steering_control_));
}

Occupant_Classification::~Occupant_Classification() {
  // @@protoc_insertion_point(destructor:osi3.Occupant.Classification)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void Occupant_Classification::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void Occupant_Classification::ArenaDtor(void* object) {
  Occupant_Classification* _this = reinterpret_cast< Occupant_Classification* >(object);
  (void)_this;
}
void Occupant_Classification::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void Occupant_Classification::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void Occupant_Classification::Clear() {
// @@protoc_insertion_point(message_clear_start:osi3.Occupant.Classification)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    ::memset(&is_driver_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&steering_control_) -
        reinterpret_cast<char*>(&is_driver_)) + sizeof(steering_control_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Occupant_Classification::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional bool is_driver = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          _Internal::set_has_is_driver(&has_bits);
          is_driver_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional .osi3.Occupant.Classification.Seat seat = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          if (PROTOBUF_PREDICT_TRUE(::osi3::Occupant_Classification_Seat_IsValid(val))) {
            _internal_set_seat(static_cast<::osi3::Occupant_Classification_Seat>(val));
          } else {
            ::PROTOBUF_NAMESPACE_ID::internal::WriteVarint(3, val, mutable_unknown_fields());
          }
        } else
          goto handle_unusual;
        continue;
      // optional .osi3.Occupant.Classification.SteeringControl steering_control = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          if (PROTOBUF_PREDICT_TRUE(::osi3::Occupant_Classification_SteeringControl_IsValid(val))) {
            _internal_set_steering_control(static_cast<::osi3::Occupant_Classification_SteeringControl>(val));
          } else {
            ::PROTOBUF_NAMESPACE_ID::internal::WriteVarint(4, val, mutable_unknown_fields());
          }
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* Occupant_Classification::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:osi3.Occupant.Classification)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional bool is_driver = 2;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(2, this->_internal_is_driver(), target);
  }

  // optional .osi3.Occupant.Classification.Seat seat = 3;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      3, this->_internal_seat(), target);
  }

  // optional .osi3.Occupant.Classification.SteeringControl steering_control = 4;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      4, this->_internal_steering_control(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:osi3.Occupant.Classification)
  return target;
}

size_t Occupant_Classification::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:osi3.Occupant.Classification)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    // optional bool is_driver = 2;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 + 1;
    }

    // optional .osi3.Occupant.Classification.Seat seat = 3;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_seat());
    }

    // optional .osi3.Occupant.Classification.SteeringControl steering_control = 4;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_steering_control());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Occupant_Classification::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    Occupant_Classification::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Occupant_Classification::GetClassData() const { return &_class_data_; }

void Occupant_Classification::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<Occupant_Classification *>(to)->MergeFrom(
      static_cast<const Occupant_Classification &>(from));
}


void Occupant_Classification::MergeFrom(const Occupant_Classification& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:osi3.Occupant.Classification)
  GOOGLE_DCHECK_NE(&from, this);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      is_driver_ = from.is_driver_;
    }
    if (cached_has_bits & 0x00000002u) {
      seat_ = from.seat_;
    }
    if (cached_has_bits & 0x00000004u) {
      steering_control_ = from.steering_control_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Occupant_Classification::CopyFrom(const Occupant_Classification& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:osi3.Occupant.Classification)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Occupant_Classification::IsInitialized() const {
  return true;
}

void Occupant_Classification::InternalSwap(Occupant_Classification* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Occupant_Classification, steering_control_)
      + sizeof(Occupant_Classification::steering_control_)
      - PROTOBUF_FIELD_OFFSET(Occupant_Classification, is_driver_)>(
          reinterpret_cast<char*>(&is_driver_),
          reinterpret_cast<char*>(&other->is_driver_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Occupant_Classification::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_osi_5foccupant_2eproto_getter, &descriptor_table_osi_5foccupant_2eproto_once,
      file_level_metadata_osi_5foccupant_2eproto[0]);
}

// ===================================================================

class Occupant::_Internal {
 public:
  using HasBits = decltype(std::declval<Occupant>()._has_bits_);
  static const ::osi3::Identifier& id(const Occupant* msg);
  static void set_has_id(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static const ::osi3::Occupant_Classification& classification(const Occupant* msg);
  static void set_has_classification(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
};

const ::osi3::Identifier&
Occupant::_Internal::id(const Occupant* msg) {
  return *msg->id_;
}
const ::osi3::Occupant_Classification&
Occupant::_Internal::classification(const Occupant* msg) {
  return *msg->classification_;
}
void Occupant::clear_id() {
  if (id_ != nullptr) id_->Clear();
  _has_bits_[0] &= ~0x00000001u;
}
void Occupant::clear_source_reference() {
  source_reference_.Clear();
}
Occupant::Occupant(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned),
  source_reference_(arena) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:osi3.Occupant)
}
Occupant::Occupant(const Occupant& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_),
      source_reference_(from.source_reference_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_id()) {
    id_ = new ::osi3::Identifier(*from.id_);
  } else {
    id_ = nullptr;
  }
  if (from._internal_has_classification()) {
    classification_ = new ::osi3::Occupant_Classification(*from.classification_);
  } else {
    classification_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:osi3.Occupant)
}

void Occupant::SharedCtor() {
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&id_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&classification_) -
    reinterpret_cast<char*>(&id_)) + sizeof(classification_));
}

Occupant::~Occupant() {
  // @@protoc_insertion_point(destructor:osi3.Occupant)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void Occupant::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete id_;
  if (this != internal_default_instance()) delete classification_;
}

void Occupant::ArenaDtor(void* object) {
  Occupant* _this = reinterpret_cast< Occupant* >(object);
  (void)_this;
}
void Occupant::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void Occupant::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void Occupant::Clear() {
// @@protoc_insertion_point(message_clear_start:osi3.Occupant)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  source_reference_.Clear();
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      GOOGLE_DCHECK(id_ != nullptr);
      id_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      GOOGLE_DCHECK(classification_ != nullptr);
      classification_->Clear();
    }
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Occupant::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional .osi3.Identifier id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_id(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional .osi3.Occupant.Classification classification = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_classification(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .osi3.ExternalReference source_reference = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_source_reference(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* Occupant::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:osi3.Occupant)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional .osi3.Identifier id = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::id(this), target, stream);
  }

  // optional .osi3.Occupant.Classification classification = 2;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        2, _Internal::classification(this), target, stream);
  }

  // repeated .osi3.ExternalReference source_reference = 3;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_source_reference_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, this->_internal_source_reference(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:osi3.Occupant)
  return target;
}

size_t Occupant::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:osi3.Occupant)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .osi3.ExternalReference source_reference = 3;
  total_size += 1UL * this->_internal_source_reference_size();
  for (const auto& msg : this->source_reference_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // optional .osi3.Identifier id = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *id_);
    }

    // optional .osi3.Occupant.Classification classification = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *classification_);
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Occupant::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    Occupant::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Occupant::GetClassData() const { return &_class_data_; }

void Occupant::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<Occupant *>(to)->MergeFrom(
      static_cast<const Occupant &>(from));
}


void Occupant::MergeFrom(const Occupant& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:osi3.Occupant)
  GOOGLE_DCHECK_NE(&from, this);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  source_reference_.MergeFrom(from.source_reference_);
  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _internal_mutable_id()->::osi3::Identifier::MergeFrom(from._internal_id());
    }
    if (cached_has_bits & 0x00000002u) {
      _internal_mutable_classification()->::osi3::Occupant_Classification::MergeFrom(from._internal_classification());
    }
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Occupant::CopyFrom(const Occupant& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:osi3.Occupant)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Occupant::IsInitialized() const {
  return true;
}

void Occupant::InternalSwap(Occupant* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  source_reference_.InternalSwap(&other->source_reference_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Occupant, classification_)
      + sizeof(Occupant::classification_)
      - PROTOBUF_FIELD_OFFSET(Occupant, id_)>(
          reinterpret_cast<char*>(&id_),
          reinterpret_cast<char*>(&other->id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Occupant::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_osi_5foccupant_2eproto_getter, &descriptor_table_osi_5foccupant_2eproto_once,
      file_level_metadata_osi_5foccupant_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace osi3
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::osi3::Occupant_Classification* Arena::CreateMaybeMessage< ::osi3::Occupant_Classification >(Arena* arena) {
  return Arena::CreateMessageInternal< ::osi3::Occupant_Classification >(arena);
}
template<> PROTOBUF_NOINLINE ::osi3::Occupant* Arena::CreateMaybeMessage< ::osi3::Occupant >(Arena* arena) {
  return Arena::CreateMessageInternal< ::osi3::Occupant >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
