// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: osi_version.proto

#include "osi_version.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace osi3 {
constexpr InterfaceVersion::InterfaceVersion(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : version_major_(0u)
  , version_minor_(0u)
  , version_patch_(0u){}
struct InterfaceVersionDefaultTypeInternal {
  constexpr InterfaceVersionDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~InterfaceVersionDefaultTypeInternal() {}
  union {
    InterfaceVersion _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT InterfaceVersionDefaultTypeInternal _InterfaceVersion_default_instance_;
}  // namespace osi3
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_osi_5fversion_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_osi_5fversion_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_osi_5fversion_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_osi_5fversion_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::osi3::InterfaceVersion, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::osi3::InterfaceVersion, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::osi3::InterfaceVersion, version_major_),
  PROTOBUF_FIELD_OFFSET(::osi3::InterfaceVersion, version_minor_),
  PROTOBUF_FIELD_OFFSET(::osi3::InterfaceVersion, version_patch_),
  0,
  1,
  2,
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 9, -1, sizeof(::osi3::InterfaceVersion)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::osi3::_InterfaceVersion_default_instance_),
};

const char descriptor_table_protodef_osi_5fversion_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\021osi_version.proto\022\004osi3\032 google/protob"
  "uf/descriptor.proto\"W\n\020InterfaceVersion\022"
  "\025\n\rversion_major\030\001 \001(\r\022\025\n\rversion_minor\030"
  "\002 \001(\r\022\025\n\rversion_patch\030\003 \001(\r:Y\n\031current_"
  "interface_version\022\034.google.protobuf.File"
  "Options\030\350\370\004 \001(\0132\026.osi3.InterfaceVersionB"
  "\024H\001\302\306\'\002\010\003\302\306\'\002\020\004\302\306\'\002\030\000"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_osi_5fversion_2eproto_deps[1] = {
  &::descriptor_table_google_2fprotobuf_2fdescriptor_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_osi_5fversion_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_osi_5fversion_2eproto = {
  false, false, 261, descriptor_table_protodef_osi_5fversion_2eproto, "osi_version.proto", 
  &descriptor_table_osi_5fversion_2eproto_once, descriptor_table_osi_5fversion_2eproto_deps, 1, 1,
  schemas, file_default_instances, TableStruct_osi_5fversion_2eproto::offsets,
  file_level_metadata_osi_5fversion_2eproto, file_level_enum_descriptors_osi_5fversion_2eproto, file_level_service_descriptors_osi_5fversion_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_osi_5fversion_2eproto_getter() {
  return &descriptor_table_osi_5fversion_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_osi_5fversion_2eproto(&descriptor_table_osi_5fversion_2eproto);
namespace osi3 {

// ===================================================================

class InterfaceVersion::_Internal {
 public:
  using HasBits = decltype(std::declval<InterfaceVersion>()._has_bits_);
  static void set_has_version_major(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_version_minor(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_version_patch(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
};

InterfaceVersion::InterfaceVersion(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:osi3.InterfaceVersion)
}
InterfaceVersion::InterfaceVersion(const InterfaceVersion& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&version_major_, &from.version_major_,
    static_cast<size_t>(reinterpret_cast<char*>(&version_patch_) -
    reinterpret_cast<char*>(&version_major_)) + sizeof(version_patch_));
  // @@protoc_insertion_point(copy_constructor:osi3.InterfaceVersion)
}

void InterfaceVersion::SharedCtor() {
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&version_major_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&version_patch_) -
    reinterpret_cast<char*>(&version_major_)) + sizeof(version_patch_));
}

InterfaceVersion::~InterfaceVersion() {
  // @@protoc_insertion_point(destructor:osi3.InterfaceVersion)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void InterfaceVersion::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void InterfaceVersion::ArenaDtor(void* object) {
  InterfaceVersion* _this = reinterpret_cast< InterfaceVersion* >(object);
  (void)_this;
}
void InterfaceVersion::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void InterfaceVersion::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void InterfaceVersion::Clear() {
// @@protoc_insertion_point(message_clear_start:osi3.InterfaceVersion)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    ::memset(&version_major_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&version_patch_) -
        reinterpret_cast<char*>(&version_major_)) + sizeof(version_patch_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* InterfaceVersion::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional uint32 version_major = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          _Internal::set_has_version_major(&has_bits);
          version_major_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional uint32 version_minor = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          _Internal::set_has_version_minor(&has_bits);
          version_minor_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional uint32 version_patch = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          _Internal::set_has_version_patch(&has_bits);
          version_patch_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* InterfaceVersion::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:osi3.InterfaceVersion)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional uint32 version_major = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(1, this->_internal_version_major(), target);
  }

  // optional uint32 version_minor = 2;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(2, this->_internal_version_minor(), target);
  }

  // optional uint32 version_patch = 3;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(3, this->_internal_version_patch(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:osi3.InterfaceVersion)
  return target;
}

size_t InterfaceVersion::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:osi3.InterfaceVersion)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    // optional uint32 version_major = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32SizePlusOne(this->_internal_version_major());
    }

    // optional uint32 version_minor = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32SizePlusOne(this->_internal_version_minor());
    }

    // optional uint32 version_patch = 3;
    if (cached_has_bits & 0x00000004u) {
      total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32SizePlusOne(this->_internal_version_patch());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData InterfaceVersion::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    InterfaceVersion::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*InterfaceVersion::GetClassData() const { return &_class_data_; }

void InterfaceVersion::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<InterfaceVersion *>(to)->MergeFrom(
      static_cast<const InterfaceVersion &>(from));
}


void InterfaceVersion::MergeFrom(const InterfaceVersion& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:osi3.InterfaceVersion)
  GOOGLE_DCHECK_NE(&from, this);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      version_major_ = from.version_major_;
    }
    if (cached_has_bits & 0x00000002u) {
      version_minor_ = from.version_minor_;
    }
    if (cached_has_bits & 0x00000004u) {
      version_patch_ = from.version_patch_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void InterfaceVersion::CopyFrom(const InterfaceVersion& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:osi3.InterfaceVersion)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool InterfaceVersion::IsInitialized() const {
  return true;
}

void InterfaceVersion::InternalSwap(InterfaceVersion* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(InterfaceVersion, version_patch_)
      + sizeof(InterfaceVersion::version_patch_)
      - PROTOBUF_FIELD_OFFSET(InterfaceVersion, version_major_)>(
          reinterpret_cast<char*>(&version_major_),
          reinterpret_cast<char*>(&other->version_major_));
}

::PROTOBUF_NAMESPACE_ID::Metadata InterfaceVersion::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_osi_5fversion_2eproto_getter, &descriptor_table_osi_5fversion_2eproto_once,
      file_level_metadata_osi_5fversion_2eproto[0]);
}
PROTOBUF_ATTRIBUTE_INIT_PRIORITY ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::MessageTypeTraits< ::osi3::InterfaceVersion >, 11, false >
  current_interface_version(kCurrentInterfaceVersionFieldNumber, ::osi3::InterfaceVersion::default_instance());

// @@protoc_insertion_point(namespace_scope)
}  // namespace osi3
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::osi3::InterfaceVersion* Arena::CreateMaybeMessage< ::osi3::InterfaceVersion >(Arena* arena) {
  return Arena::CreateMessageInternal< ::osi3::InterfaceVersion >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
