// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: osi_detectedtrafficlight.proto

#include "osi_detectedtrafficlight.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace osi3 {
constexpr DetectedTrafficLight_CandidateTrafficLight::DetectedTrafficLight_CandidateTrafficLight(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : classification_(nullptr)
  , probability_(0){}
struct DetectedTrafficLight_CandidateTrafficLightDefaultTypeInternal {
  constexpr DetectedTrafficLight_CandidateTrafficLightDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~DetectedTrafficLight_CandidateTrafficLightDefaultTypeInternal() {}
  union {
    DetectedTrafficLight_CandidateTrafficLight _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT DetectedTrafficLight_CandidateTrafficLightDefaultTypeInternal _DetectedTrafficLight_CandidateTrafficLight_default_instance_;
constexpr DetectedTrafficLight::DetectedTrafficLight(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : candidate_()
  , header_(nullptr)
  , base_(nullptr)
  , base_rmse_(nullptr)
  , color_description_(nullptr){}
struct DetectedTrafficLightDefaultTypeInternal {
  constexpr DetectedTrafficLightDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~DetectedTrafficLightDefaultTypeInternal() {}
  union {
    DetectedTrafficLight _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT DetectedTrafficLightDefaultTypeInternal _DetectedTrafficLight_default_instance_;
}  // namespace osi3
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_osi_5fdetectedtrafficlight_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_osi_5fdetectedtrafficlight_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_osi_5fdetectedtrafficlight_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_osi_5fdetectedtrafficlight_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::osi3::DetectedTrafficLight_CandidateTrafficLight, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::osi3::DetectedTrafficLight_CandidateTrafficLight, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::osi3::DetectedTrafficLight_CandidateTrafficLight, probability_),
  PROTOBUF_FIELD_OFFSET(::osi3::DetectedTrafficLight_CandidateTrafficLight, classification_),
  1,
  0,
  PROTOBUF_FIELD_OFFSET(::osi3::DetectedTrafficLight, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::osi3::DetectedTrafficLight, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::osi3::DetectedTrafficLight, header_),
  PROTOBUF_FIELD_OFFSET(::osi3::DetectedTrafficLight, base_),
  PROTOBUF_FIELD_OFFSET(::osi3::DetectedTrafficLight, base_rmse_),
  PROTOBUF_FIELD_OFFSET(::osi3::DetectedTrafficLight, candidate_),
  PROTOBUF_FIELD_OFFSET(::osi3::DetectedTrafficLight, color_description_),
  0,
  1,
  2,
  ~0u,
  3,
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 8, -1, sizeof(::osi3::DetectedTrafficLight_CandidateTrafficLight)},
  { 10, 21, -1, sizeof(::osi3::DetectedTrafficLight)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::osi3::_DetectedTrafficLight_CandidateTrafficLight_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::osi3::_DetectedTrafficLight_default_instance_),
};

const char descriptor_table_protodef_osi_5fdetectedtrafficlight_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\036osi_detectedtrafficlight.proto\022\004osi3\032\020"
  "osi_common.proto\032\026osi_trafficlight.proto"
  "\032\030osi_detectedobject.proto\"\356\002\n\024DetectedT"
  "rafficLight\022(\n\006header\030\001 \001(\0132\030.osi3.Detec"
  "tedItemHeader\022\"\n\004base\030\002 \001(\0132\024.osi3.BaseS"
  "tationary\022\'\n\tbase_rmse\030\003 \001(\0132\024.osi3.Base"
  "Stationary\022C\n\tcandidate\030\004 \003(\01320.osi3.Det"
  "ectedTrafficLight.CandidateTrafficLight\022"
  "1\n\021color_description\030\005 \001(\0132\026.osi3.ColorD"
  "escription\032g\n\025CandidateTrafficLight\022\023\n\013p"
  "robability\030\001 \001(\001\0229\n\016classification\030\002 \001(\013"
  "2!.osi3.TrafficLight.ClassificationB\002H\001"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_osi_5fdetectedtrafficlight_2eproto_deps[3] = {
  &::descriptor_table_osi_5fcommon_2eproto,
  &::descriptor_table_osi_5fdetectedobject_2eproto,
  &::descriptor_table_osi_5ftrafficlight_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_osi_5fdetectedtrafficlight_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_osi_5fdetectedtrafficlight_2eproto = {
  false, false, 479, descriptor_table_protodef_osi_5fdetectedtrafficlight_2eproto, "osi_detectedtrafficlight.proto", 
  &descriptor_table_osi_5fdetectedtrafficlight_2eproto_once, descriptor_table_osi_5fdetectedtrafficlight_2eproto_deps, 3, 2,
  schemas, file_default_instances, TableStruct_osi_5fdetectedtrafficlight_2eproto::offsets,
  file_level_metadata_osi_5fdetectedtrafficlight_2eproto, file_level_enum_descriptors_osi_5fdetectedtrafficlight_2eproto, file_level_service_descriptors_osi_5fdetectedtrafficlight_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_osi_5fdetectedtrafficlight_2eproto_getter() {
  return &descriptor_table_osi_5fdetectedtrafficlight_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_osi_5fdetectedtrafficlight_2eproto(&descriptor_table_osi_5fdetectedtrafficlight_2eproto);
namespace osi3 {

// ===================================================================

class DetectedTrafficLight_CandidateTrafficLight::_Internal {
 public:
  using HasBits = decltype(std::declval<DetectedTrafficLight_CandidateTrafficLight>()._has_bits_);
  static void set_has_probability(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static const ::osi3::TrafficLight_Classification& classification(const DetectedTrafficLight_CandidateTrafficLight* msg);
  static void set_has_classification(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

const ::osi3::TrafficLight_Classification&
DetectedTrafficLight_CandidateTrafficLight::_Internal::classification(const DetectedTrafficLight_CandidateTrafficLight* msg) {
  return *msg->classification_;
}
void DetectedTrafficLight_CandidateTrafficLight::clear_classification() {
  if (classification_ != nullptr) classification_->Clear();
  _has_bits_[0] &= ~0x00000001u;
}
DetectedTrafficLight_CandidateTrafficLight::DetectedTrafficLight_CandidateTrafficLight(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:osi3.DetectedTrafficLight.CandidateTrafficLight)
}
DetectedTrafficLight_CandidateTrafficLight::DetectedTrafficLight_CandidateTrafficLight(const DetectedTrafficLight_CandidateTrafficLight& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_classification()) {
    classification_ = new ::osi3::TrafficLight_Classification(*from.classification_);
  } else {
    classification_ = nullptr;
  }
  probability_ = from.probability_;
  // @@protoc_insertion_point(copy_constructor:osi3.DetectedTrafficLight.CandidateTrafficLight)
}

void DetectedTrafficLight_CandidateTrafficLight::SharedCtor() {
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&classification_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&probability_) -
    reinterpret_cast<char*>(&classification_)) + sizeof(probability_));
}

DetectedTrafficLight_CandidateTrafficLight::~DetectedTrafficLight_CandidateTrafficLight() {
  // @@protoc_insertion_point(destructor:osi3.DetectedTrafficLight.CandidateTrafficLight)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void DetectedTrafficLight_CandidateTrafficLight::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete classification_;
}

void DetectedTrafficLight_CandidateTrafficLight::ArenaDtor(void* object) {
  DetectedTrafficLight_CandidateTrafficLight* _this = reinterpret_cast< DetectedTrafficLight_CandidateTrafficLight* >(object);
  (void)_this;
}
void DetectedTrafficLight_CandidateTrafficLight::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void DetectedTrafficLight_CandidateTrafficLight::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void DetectedTrafficLight_CandidateTrafficLight::Clear() {
// @@protoc_insertion_point(message_clear_start:osi3.DetectedTrafficLight.CandidateTrafficLight)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    GOOGLE_DCHECK(classification_ != nullptr);
    classification_->Clear();
  }
  probability_ = 0;
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* DetectedTrafficLight_CandidateTrafficLight::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional double probability = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 9)) {
          _Internal::set_has_probability(&has_bits);
          probability_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // optional .osi3.TrafficLight.Classification classification = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_classification(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* DetectedTrafficLight_CandidateTrafficLight::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:osi3.DetectedTrafficLight.CandidateTrafficLight)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional double probability = 1;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(1, this->_internal_probability(), target);
  }

  // optional .osi3.TrafficLight.Classification classification = 2;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        2, _Internal::classification(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:osi3.DetectedTrafficLight.CandidateTrafficLight)
  return target;
}

size_t DetectedTrafficLight_CandidateTrafficLight::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:osi3.DetectedTrafficLight.CandidateTrafficLight)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // optional .osi3.TrafficLight.Classification classification = 2;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *classification_);
    }

    // optional double probability = 1;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 + 8;
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData DetectedTrafficLight_CandidateTrafficLight::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    DetectedTrafficLight_CandidateTrafficLight::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*DetectedTrafficLight_CandidateTrafficLight::GetClassData() const { return &_class_data_; }

void DetectedTrafficLight_CandidateTrafficLight::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<DetectedTrafficLight_CandidateTrafficLight *>(to)->MergeFrom(
      static_cast<const DetectedTrafficLight_CandidateTrafficLight &>(from));
}


void DetectedTrafficLight_CandidateTrafficLight::MergeFrom(const DetectedTrafficLight_CandidateTrafficLight& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:osi3.DetectedTrafficLight.CandidateTrafficLight)
  GOOGLE_DCHECK_NE(&from, this);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _internal_mutable_classification()->::osi3::TrafficLight_Classification::MergeFrom(from._internal_classification());
    }
    if (cached_has_bits & 0x00000002u) {
      probability_ = from.probability_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void DetectedTrafficLight_CandidateTrafficLight::CopyFrom(const DetectedTrafficLight_CandidateTrafficLight& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:osi3.DetectedTrafficLight.CandidateTrafficLight)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DetectedTrafficLight_CandidateTrafficLight::IsInitialized() const {
  return true;
}

void DetectedTrafficLight_CandidateTrafficLight::InternalSwap(DetectedTrafficLight_CandidateTrafficLight* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(DetectedTrafficLight_CandidateTrafficLight, probability_)
      + sizeof(DetectedTrafficLight_CandidateTrafficLight::probability_)
      - PROTOBUF_FIELD_OFFSET(DetectedTrafficLight_CandidateTrafficLight, classification_)>(
          reinterpret_cast<char*>(&classification_),
          reinterpret_cast<char*>(&other->classification_));
}

::PROTOBUF_NAMESPACE_ID::Metadata DetectedTrafficLight_CandidateTrafficLight::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_osi_5fdetectedtrafficlight_2eproto_getter, &descriptor_table_osi_5fdetectedtrafficlight_2eproto_once,
      file_level_metadata_osi_5fdetectedtrafficlight_2eproto[0]);
}

// ===================================================================

class DetectedTrafficLight::_Internal {
 public:
  using HasBits = decltype(std::declval<DetectedTrafficLight>()._has_bits_);
  static const ::osi3::DetectedItemHeader& header(const DetectedTrafficLight* msg);
  static void set_has_header(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static const ::osi3::BaseStationary& base(const DetectedTrafficLight* msg);
  static void set_has_base(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static const ::osi3::BaseStationary& base_rmse(const DetectedTrafficLight* msg);
  static void set_has_base_rmse(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static const ::osi3::ColorDescription& color_description(const DetectedTrafficLight* msg);
  static void set_has_color_description(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
};

const ::osi3::DetectedItemHeader&
DetectedTrafficLight::_Internal::header(const DetectedTrafficLight* msg) {
  return *msg->header_;
}
const ::osi3::BaseStationary&
DetectedTrafficLight::_Internal::base(const DetectedTrafficLight* msg) {
  return *msg->base_;
}
const ::osi3::BaseStationary&
DetectedTrafficLight::_Internal::base_rmse(const DetectedTrafficLight* msg) {
  return *msg->base_rmse_;
}
const ::osi3::ColorDescription&
DetectedTrafficLight::_Internal::color_description(const DetectedTrafficLight* msg) {
  return *msg->color_description_;
}
void DetectedTrafficLight::clear_header() {
  if (header_ != nullptr) header_->Clear();
  _has_bits_[0] &= ~0x00000001u;
}
void DetectedTrafficLight::clear_base() {
  if (base_ != nullptr) base_->Clear();
  _has_bits_[0] &= ~0x00000002u;
}
void DetectedTrafficLight::clear_base_rmse() {
  if (base_rmse_ != nullptr) base_rmse_->Clear();
  _has_bits_[0] &= ~0x00000004u;
}
void DetectedTrafficLight::clear_color_description() {
  if (color_description_ != nullptr) color_description_->Clear();
  _has_bits_[0] &= ~0x00000008u;
}
DetectedTrafficLight::DetectedTrafficLight(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned),
  candidate_(arena) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:osi3.DetectedTrafficLight)
}
DetectedTrafficLight::DetectedTrafficLight(const DetectedTrafficLight& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_),
      candidate_(from.candidate_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_header()) {
    header_ = new ::osi3::DetectedItemHeader(*from.header_);
  } else {
    header_ = nullptr;
  }
  if (from._internal_has_base()) {
    base_ = new ::osi3::BaseStationary(*from.base_);
  } else {
    base_ = nullptr;
  }
  if (from._internal_has_base_rmse()) {
    base_rmse_ = new ::osi3::BaseStationary(*from.base_rmse_);
  } else {
    base_rmse_ = nullptr;
  }
  if (from._internal_has_color_description()) {
    color_description_ = new ::osi3::ColorDescription(*from.color_description_);
  } else {
    color_description_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:osi3.DetectedTrafficLight)
}

void DetectedTrafficLight::SharedCtor() {
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&header_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&color_description_) -
    reinterpret_cast<char*>(&header_)) + sizeof(color_description_));
}

DetectedTrafficLight::~DetectedTrafficLight() {
  // @@protoc_insertion_point(destructor:osi3.DetectedTrafficLight)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void DetectedTrafficLight::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete header_;
  if (this != internal_default_instance()) delete base_;
  if (this != internal_default_instance()) delete base_rmse_;
  if (this != internal_default_instance()) delete color_description_;
}

void DetectedTrafficLight::ArenaDtor(void* object) {
  DetectedTrafficLight* _this = reinterpret_cast< DetectedTrafficLight* >(object);
  (void)_this;
}
void DetectedTrafficLight::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void DetectedTrafficLight::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void DetectedTrafficLight::Clear() {
// @@protoc_insertion_point(message_clear_start:osi3.DetectedTrafficLight)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  candidate_.Clear();
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    if (cached_has_bits & 0x00000001u) {
      GOOGLE_DCHECK(header_ != nullptr);
      header_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      GOOGLE_DCHECK(base_ != nullptr);
      base_->Clear();
    }
    if (cached_has_bits & 0x00000004u) {
      GOOGLE_DCHECK(base_rmse_ != nullptr);
      base_rmse_->Clear();
    }
    if (cached_has_bits & 0x00000008u) {
      GOOGLE_DCHECK(color_description_ != nullptr);
      color_description_->Clear();
    }
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* DetectedTrafficLight::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional .osi3.DetectedItemHeader header = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_header(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional .osi3.BaseStationary base = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_base(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional .osi3.BaseStationary base_rmse = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_base_rmse(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .osi3.DetectedTrafficLight.CandidateTrafficLight candidate = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_candidate(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<34>(ptr));
        } else
          goto handle_unusual;
        continue;
      // optional .osi3.ColorDescription color_description = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_color_description(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* DetectedTrafficLight::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:osi3.DetectedTrafficLight)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional .osi3.DetectedItemHeader header = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::header(this), target, stream);
  }

  // optional .osi3.BaseStationary base = 2;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        2, _Internal::base(this), target, stream);
  }

  // optional .osi3.BaseStationary base_rmse = 3;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        3, _Internal::base_rmse(this), target, stream);
  }

  // repeated .osi3.DetectedTrafficLight.CandidateTrafficLight candidate = 4;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_candidate_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, this->_internal_candidate(i), target, stream);
  }

  // optional .osi3.ColorDescription color_description = 5;
  if (cached_has_bits & 0x00000008u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        5, _Internal::color_description(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:osi3.DetectedTrafficLight)
  return target;
}

size_t DetectedTrafficLight::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:osi3.DetectedTrafficLight)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .osi3.DetectedTrafficLight.CandidateTrafficLight candidate = 4;
  total_size += 1UL * this->_internal_candidate_size();
  for (const auto& msg : this->candidate_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    // optional .osi3.DetectedItemHeader header = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *header_);
    }

    // optional .osi3.BaseStationary base = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *base_);
    }

    // optional .osi3.BaseStationary base_rmse = 3;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *base_rmse_);
    }

    // optional .osi3.ColorDescription color_description = 5;
    if (cached_has_bits & 0x00000008u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *color_description_);
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData DetectedTrafficLight::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    DetectedTrafficLight::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*DetectedTrafficLight::GetClassData() const { return &_class_data_; }

void DetectedTrafficLight::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<DetectedTrafficLight *>(to)->MergeFrom(
      static_cast<const DetectedTrafficLight &>(from));
}


void DetectedTrafficLight::MergeFrom(const DetectedTrafficLight& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:osi3.DetectedTrafficLight)
  GOOGLE_DCHECK_NE(&from, this);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  candidate_.MergeFrom(from.candidate_);
  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    if (cached_has_bits & 0x00000001u) {
      _internal_mutable_header()->::osi3::DetectedItemHeader::MergeFrom(from._internal_header());
    }
    if (cached_has_bits & 0x00000002u) {
      _internal_mutable_base()->::osi3::BaseStationary::MergeFrom(from._internal_base());
    }
    if (cached_has_bits & 0x00000004u) {
      _internal_mutable_base_rmse()->::osi3::BaseStationary::MergeFrom(from._internal_base_rmse());
    }
    if (cached_has_bits & 0x00000008u) {
      _internal_mutable_color_description()->::osi3::ColorDescription::MergeFrom(from._internal_color_description());
    }
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void DetectedTrafficLight::CopyFrom(const DetectedTrafficLight& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:osi3.DetectedTrafficLight)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DetectedTrafficLight::IsInitialized() const {
  return true;
}

void DetectedTrafficLight::InternalSwap(DetectedTrafficLight* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  candidate_.InternalSwap(&other->candidate_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(DetectedTrafficLight, color_description_)
      + sizeof(DetectedTrafficLight::color_description_)
      - PROTOBUF_FIELD_OFFSET(DetectedTrafficLight, header_)>(
          reinterpret_cast<char*>(&header_),
          reinterpret_cast<char*>(&other->header_));
}

::PROTOBUF_NAMESPACE_ID::Metadata DetectedTrafficLight::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_osi_5fdetectedtrafficlight_2eproto_getter, &descriptor_table_osi_5fdetectedtrafficlight_2eproto_once,
      file_level_metadata_osi_5fdetectedtrafficlight_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace osi3
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::osi3::DetectedTrafficLight_CandidateTrafficLight* Arena::CreateMaybeMessage< ::osi3::DetectedTrafficLight_CandidateTrafficLight >(Arena* arena) {
  return Arena::CreateMessageInternal< ::osi3::DetectedTrafficLight_CandidateTrafficLight >(arena);
}
template<> PROTOBUF_NOINLINE ::osi3::DetectedTrafficLight* Arena::CreateMaybeMessage< ::osi3::DetectedTrafficLight >(Arena* arena) {
  return Arena::CreateMessageInternal< ::osi3::DetectedTrafficLight >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
