// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: osi_datarecording.proto

#include "osi_datarecording.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace osi3 {
constexpr SensorDataSeries::SensorDataSeries(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : sensor_data_(){}
struct SensorDataSeriesDefaultTypeInternal {
  constexpr SensorDataSeriesDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~SensorDataSeriesDefaultTypeInternal() {}
  union {
    SensorDataSeries _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT SensorDataSeriesDefaultTypeInternal _SensorDataSeries_default_instance_;
constexpr SensorDataSeriesList::SensorDataSeriesList(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : sensor_(){}
struct SensorDataSeriesListDefaultTypeInternal {
  constexpr SensorDataSeriesListDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~SensorDataSeriesListDefaultTypeInternal() {}
  union {
    SensorDataSeriesList _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT SensorDataSeriesListDefaultTypeInternal _SensorDataSeriesList_default_instance_;
}  // namespace osi3
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_osi_5fdatarecording_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_osi_5fdatarecording_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_osi_5fdatarecording_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_osi_5fdatarecording_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::osi3::SensorDataSeries, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::osi3::SensorDataSeries, sensor_data_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::osi3::SensorDataSeriesList, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::osi3::SensorDataSeriesList, sensor_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::osi3::SensorDataSeries)},
  { 7, -1, -1, sizeof(::osi3::SensorDataSeriesList)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::osi3::_SensorDataSeries_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::osi3::_SensorDataSeriesList_default_instance_),
};

const char descriptor_table_protodef_osi_5fdatarecording_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\027osi_datarecording.proto\022\004osi3\032\024osi_sen"
  "sordata.proto\"9\n\020SensorDataSeries\022%\n\013sen"
  "sor_data\030\001 \003(\0132\020.osi3.SensorData\">\n\024Sens"
  "orDataSeriesList\022&\n\006sensor\030\001 \003(\0132\026.osi3."
  "SensorDataSeriesB\002H\001"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_osi_5fdatarecording_2eproto_deps[1] = {
  &::descriptor_table_osi_5fsensordata_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_osi_5fdatarecording_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_osi_5fdatarecording_2eproto = {
  false, false, 180, descriptor_table_protodef_osi_5fdatarecording_2eproto, "osi_datarecording.proto", 
  &descriptor_table_osi_5fdatarecording_2eproto_once, descriptor_table_osi_5fdatarecording_2eproto_deps, 1, 2,
  schemas, file_default_instances, TableStruct_osi_5fdatarecording_2eproto::offsets,
  file_level_metadata_osi_5fdatarecording_2eproto, file_level_enum_descriptors_osi_5fdatarecording_2eproto, file_level_service_descriptors_osi_5fdatarecording_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_osi_5fdatarecording_2eproto_getter() {
  return &descriptor_table_osi_5fdatarecording_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_osi_5fdatarecording_2eproto(&descriptor_table_osi_5fdatarecording_2eproto);
namespace osi3 {

// ===================================================================

class SensorDataSeries::_Internal {
 public:
};

void SensorDataSeries::clear_sensor_data() {
  sensor_data_.Clear();
}
SensorDataSeries::SensorDataSeries(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned),
  sensor_data_(arena) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:osi3.SensorDataSeries)
}
SensorDataSeries::SensorDataSeries(const SensorDataSeries& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      sensor_data_(from.sensor_data_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:osi3.SensorDataSeries)
}

void SensorDataSeries::SharedCtor() {
}

SensorDataSeries::~SensorDataSeries() {
  // @@protoc_insertion_point(destructor:osi3.SensorDataSeries)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void SensorDataSeries::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void SensorDataSeries::ArenaDtor(void* object) {
  SensorDataSeries* _this = reinterpret_cast< SensorDataSeries* >(object);
  (void)_this;
}
void SensorDataSeries::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void SensorDataSeries::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void SensorDataSeries::Clear() {
// @@protoc_insertion_point(message_clear_start:osi3.SensorDataSeries)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  sensor_data_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SensorDataSeries::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .osi3.SensorData sensor_data = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_sensor_data(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* SensorDataSeries::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:osi3.SensorDataSeries)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .osi3.SensorData sensor_data = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_sensor_data_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, this->_internal_sensor_data(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:osi3.SensorDataSeries)
  return target;
}

size_t SensorDataSeries::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:osi3.SensorDataSeries)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .osi3.SensorData sensor_data = 1;
  total_size += 1UL * this->_internal_sensor_data_size();
  for (const auto& msg : this->sensor_data_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SensorDataSeries::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    SensorDataSeries::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SensorDataSeries::GetClassData() const { return &_class_data_; }

void SensorDataSeries::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<SensorDataSeries *>(to)->MergeFrom(
      static_cast<const SensorDataSeries &>(from));
}


void SensorDataSeries::MergeFrom(const SensorDataSeries& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:osi3.SensorDataSeries)
  GOOGLE_DCHECK_NE(&from, this);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  sensor_data_.MergeFrom(from.sensor_data_);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SensorDataSeries::CopyFrom(const SensorDataSeries& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:osi3.SensorDataSeries)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SensorDataSeries::IsInitialized() const {
  return true;
}

void SensorDataSeries::InternalSwap(SensorDataSeries* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  sensor_data_.InternalSwap(&other->sensor_data_);
}

::PROTOBUF_NAMESPACE_ID::Metadata SensorDataSeries::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_osi_5fdatarecording_2eproto_getter, &descriptor_table_osi_5fdatarecording_2eproto_once,
      file_level_metadata_osi_5fdatarecording_2eproto[0]);
}

// ===================================================================

class SensorDataSeriesList::_Internal {
 public:
};

SensorDataSeriesList::SensorDataSeriesList(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned),
  sensor_(arena) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:osi3.SensorDataSeriesList)
}
SensorDataSeriesList::SensorDataSeriesList(const SensorDataSeriesList& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      sensor_(from.sensor_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:osi3.SensorDataSeriesList)
}

void SensorDataSeriesList::SharedCtor() {
}

SensorDataSeriesList::~SensorDataSeriesList() {
  // @@protoc_insertion_point(destructor:osi3.SensorDataSeriesList)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void SensorDataSeriesList::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void SensorDataSeriesList::ArenaDtor(void* object) {
  SensorDataSeriesList* _this = reinterpret_cast< SensorDataSeriesList* >(object);
  (void)_this;
}
void SensorDataSeriesList::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void SensorDataSeriesList::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void SensorDataSeriesList::Clear() {
// @@protoc_insertion_point(message_clear_start:osi3.SensorDataSeriesList)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  sensor_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SensorDataSeriesList::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .osi3.SensorDataSeries sensor = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_sensor(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* SensorDataSeriesList::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:osi3.SensorDataSeriesList)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .osi3.SensorDataSeries sensor = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_sensor_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, this->_internal_sensor(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:osi3.SensorDataSeriesList)
  return target;
}

size_t SensorDataSeriesList::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:osi3.SensorDataSeriesList)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .osi3.SensorDataSeries sensor = 1;
  total_size += 1UL * this->_internal_sensor_size();
  for (const auto& msg : this->sensor_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SensorDataSeriesList::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    SensorDataSeriesList::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SensorDataSeriesList::GetClassData() const { return &_class_data_; }

void SensorDataSeriesList::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<SensorDataSeriesList *>(to)->MergeFrom(
      static_cast<const SensorDataSeriesList &>(from));
}


void SensorDataSeriesList::MergeFrom(const SensorDataSeriesList& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:osi3.SensorDataSeriesList)
  GOOGLE_DCHECK_NE(&from, this);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  sensor_.MergeFrom(from.sensor_);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SensorDataSeriesList::CopyFrom(const SensorDataSeriesList& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:osi3.SensorDataSeriesList)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SensorDataSeriesList::IsInitialized() const {
  return true;
}

void SensorDataSeriesList::InternalSwap(SensorDataSeriesList* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  sensor_.InternalSwap(&other->sensor_);
}

::PROTOBUF_NAMESPACE_ID::Metadata SensorDataSeriesList::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_osi_5fdatarecording_2eproto_getter, &descriptor_table_osi_5fdatarecording_2eproto_once,
      file_level_metadata_osi_5fdatarecording_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace osi3
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::osi3::SensorDataSeries* Arena::CreateMaybeMessage< ::osi3::SensorDataSeries >(Arena* arena) {
  return Arena::CreateMessageInternal< ::osi3::SensorDataSeries >(arena);
}
template<> PROTOBUF_NOINLINE ::osi3::SensorDataSeriesList* Arena::CreateMaybeMessage< ::osi3::SensorDataSeriesList >(Arena* arena) {
  return Arena::CreateMessageInternal< ::osi3::SensorDataSeriesList >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
